Gemfile.lock, app/models/creation.rb, app/models/event.rb, app/models/user.rb, db/seeds.rb
=> models optimized and join tables tested

Gemfile, Gemfile.lock, app/models/creation.rb, app/models/event.rb, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20220301093949_create_active_storage_tables.active_storage.rb, db/schema.rb
please review, Cloudinary added and photos added in tables users creations and events
=> cloudinary added

Gemfile.lock, app/models/creation.rb, app/models/event.rb, app/models/user.rb, db/seeds.rb
=> seeds created

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/layouts/_navbar.html.erb, app/views/layouts/_navbar_content.html.erb, app/views/layouts/_navbarkeep.html.erb, app/views/layouts/application.html.erb
please review the responsive navbar
=> navbar done

app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb
please review, button link changed in homepage just to be able access it and same for dashboard and if loop
=> homepage button route changed and dashboard if resolved, the pages work

app/views/layouts/_navbar.html.erb, app/views/layouts/_navbar_content.html.erb
=> navbar links added and sticky top

app/views/creations/new.html.erb, app/views/pages/new.html.erb, app/views/partials/_form.html.erb
error with pathing cause new to not render, now working
=> moved new page from pages to creations

app/controllers/creations_controller.rb, app/views/layouts/_footer.html.erb
expanded footer and made sure new is working
=> new is working

app/controllers/dashboard_controller.rb, app/views/dashboard/attendedevents.html.erb, app/views/dashboard/likedcreations.html.erb, app/views/dashboard/mycreations.html.erb, app/views/dashboard/myevents.html.erb, app/views/partials/_event_card.html.erb
=> dashboard not completed yet

app/views/creations/show.html.erb, db/seeds.rb
=> Seeds with photos

app/controllers/events_controller.rb, app/views/creations/new.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/layouts/_navbar_content.html.erb, app/views/partials/_event_card.html.erb, app/views/partials/_form-event.html.erb, config/routes.rb
=> showpage event and event creation

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_participation-button.scss, app/controllers/participations_controller.rb, app/javascript/controllers/participation_controller.js, app/views/partials/_event_card.html.erb, app/views/partials/_participation.html.erb, config/routes.rb
=> stimulus for participations

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/pages/_home.scss, app/views/dashboard/attendedevents.html.erb, app/views/dashboard/likedcreations.html.erb, app/views/dashboard/mycreations.html.erb, app/views/dashboard/myevents.html.erb, app/views/pages/main.html.erb, app/views/partials/_card.html.erb
=> new card container for dashboard and in main for creations

app/views/events/show.html.erb, db/seeds.rb
please review, title and participate button added
=> New show event

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_dashboard-menu.scss, app/assets/stylesheets/components/_index.scss, app/views/dashboard/attendedevents.html.erb, app/views/dashboard/likedcreations.html.erb, app/views/dashboard/mycreations.html.erb, app/views/dashboard/myevents.html.erb, app/views/events/show.html.erb, app/views/partials/_card.html.erb, app/views/partials/_dashboard-menu.html.erb
=> Dashboard menu

app/views/creations/show.html.erb
changed the frontend of creation showpage
=> creation showpage improved

app/controllers/pages_controller.rb, app/views/layouts/_categories.html.erb, app/views/pages/home.html.erb, app/views/pages/main.html.erb
=> added index filter

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_main.scss, app/views/pages/main.html.erb, app/views/partials/_card.html.erb, app/views/partials/_event_card.html.erb, db/seeds.rb
=> cards modified, links don't work anymore... to be fixed

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_main.scss, app/views/events/show.html.erb, app/views/layouts/_categories.html.erb, app/views/pages/home.html.erb, app/views/pages/main.html.erb, app/views/partials/_card.html.erb, app/views/partials/_event_card.html.erb
=> last teaks for presentation

app/views/layouts/_navbar_content.html.erb, app/views/pages/main.html.erb
moved dashboard into user dropdown menu
=> fixed dashboard

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_category.scss, app/assets/stylesheets/components/_index.scss, app/controllers/creations_controller.rb, app/controllers/events_controller.rb, app/controllers/pages_controller.rb, app/views/creations/show.html.erb, app/views/events/show.html.erb, app/views/partials/_card.html.erb, app/views/partials/_event_card.html.erb, app/views/partials/_form-event.html.erb
=> Categ icons on cards

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/pages/_main.scss, app/views/layouts/_categories.html.erb, app/views/partials/_event_card.html.erb, db/seeds.rb
=> event cards done and category names added

app/controllers/dashboard_controller.rb
=> categories added to controller

app/controllers/pages_controller.rb, app/views/creations/show.html.erb, app/views/events/show.html.erb, app/views/layouts/_creations_scroll.html.erb, app/views/partials/_card.html.erb
=> created partial for showing creations in events

app/controllers/pages_controller.rb
=> filter is now working

app/assets/stylesheets/components/_form-event.scss, app/assets/stylesheets/components/_index.scss, app/views/partials/_form-event.html.erb
=> size for creation images in new event adapted

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_index.scss, app/channels/chatroom_channel.rb, app/controllers/chatrooms_controller.rb, app/controllers/creations_controller.rb, app/controllers/events_controller.rb, app/controllers/messages_controller.rb, app/javascript/controllers/chatroom_subscription_controller.js, app/models/chatroom.rb, app/models/message.rb, app/models/user.rb, app/views/chatrooms/_new_chatroom.html.erb, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, app/views/creations/show.html.erb, app/views/events/show.html.erb, app/views/layouts/_navbar_content.html.erb, app/views/messages/_message.html.erb, config/cable.yml, config/routes.rb, db/migrate/20220308083233_create_chatrooms.rb, db/migrate/20220308083239_create_messages.rb, db/migrate/20220308092035_add_user_to_chatrooms.rb, db/schema.rb, db/seeds.rb, test/channels/chatroom_channel_test.rb, test/controllers/chatrooms_controller_test.rb, test/controllers/messages_controller_test.rb, test/models/chatroom_test.rb, test/models/message_test.rb
lots of new things for chat added, pls review
=> Chat function

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_create-event-btn.scss, app/assets/stylesheets/components/_creation-card.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/main.html.erb, app/views/partials/_creation-card.html.erb, app/views/partials/_form-event.html.erb, app/views/partials/_like.html.erb
=> new creation card design for main page, also liked partial changed a bit

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/_navbar.html.erb, app/views/layouts/_navbar_content.html.erb
=> navbar reworked

app/assets/stylesheets/components/_category.scss, app/assets/stylesheets/components/_creation-card.scss, app/assets/stylesheets/components/_like-button.scss, app/views/creations/show.html.erb, app/views/dashboard/likedcreations.html.erb, app/views/dashboard/mycreations.html.erb, app/views/partials/_creation-card.html.erb, app/views/partials/_like.html.erb
=> last changes on creation cards on showpage creations

app/assets/stylesheets/components/_creation-card.scss
=> card width

db/seeds.rb
=> added new seeds

app/assets/stylesheets/components/_create-event-btn.scss, app/views/partials/_form.html.erb
=> add creation button changed

db/seeds.rb
=> updated description

app/views/layouts/application.html.erb
=> longer title 20 char minimum

app/assets/stylesheets/components/_dashboard-menu.scss, app/views/partials/_dashboard-menu.html.erb
=> New dashboard menu

db/seeds.rb
=> longer descriptions added to seeds

app/views/partials/_card.html.erb, app/views/partials/_creation-card.html.erb, app/views/partials/_event_card.html.erb, app/views/partials/_like.html.erb, app/views/partials/_participation.html.erb
=> card links now on whole pages
